/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpapbodbd.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projectpapbodbd.ConnectionDatabase;
import projectpapbodbd.objek.Denda;

public class FormDenda extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    Connection conn;
    DefaultTableModel model;
    private FormMenu formMenu;
    private String kodeuser;
    private String role;

    public FormDenda(FormMenu formMenu, String kodeuser, String role) {
        this.formMenu = formMenu;
        this.kodeuser = kodeuser;
        this.role = role;
        initComponents();
        
        ConnectionDatabase database = new ConnectionDatabase();
        conn = database.openConnection();

        model = new DefaultTableModel();
        tabledenda.setModel(model);

        model.addColumn("No");
        model.addColumn("Kode Denda");
        model.addColumn("Jumlah Denda");
        model.addColumn("Kode Peminjaman");
        model.addColumn("Kode Buku");
        model.addColumn("Kode Anggota");

        showData();
        txtuser.setText(this.kodeuser);
    }
    private void showData() {
    try {
        st = conn.createStatement();
        rs = st.executeQuery("SELECT d.kodedenda, d.jumlahdenda, d.peminjamanbuku_kodepinjam, p.buku_kodebuku, p.anggota_kodeuser FROM denda d JOIN peminjamanbuku p ON p.kodepinjam = d.peminjamanbuku_kodepinjam WHERE keterangan is null");

        int no = 1;

        while (rs.next()) {
            Object[] data = {
                no++,
                rs.getString("kodedenda"),
                rs.getString("jumlahdenda"),
                rs.getString("peminjamanbuku_kodepinjam"),
                rs.getString("buku_kodebuku"),
                rs.getString("anggota_kodeuser")
            };

            model.addRow(data);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabledenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnkonfirmasi = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtkodedenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpeminjam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtkodebuku = new javax.swing.JTextField();
        txtkodepinjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabledenda.setBackground(new java.awt.Color(204, 204, 204));
        tabledenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledenda);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Data Denda Anggota");

        txtuser.setEditable(false);

        jLabel7.setText("User");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnkonfirmasi.setText("Konfirmasi");
        btnkonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkonfirmasiActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jLabel8.setText("Tombol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnkonfirmasi)
                .addGap(18, 18, 18)
                .addComponent(btnbatal)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal)
                    .addComponent(btnkonfirmasi))
                .addGap(16, 16, 16))
        );

        txtkodedenda.setEditable(false);

        jLabel6.setText("Kode Denda");

        txtpeminjam.setEditable(false);

        jLabel3.setText("Peminjam");

        txtkodebuku.setEditable(false);

        txtkodepinjam.setEditable(false);

        jLabel5.setText("Kode Pinjam");

        jLabel4.setText("Kode Buku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtkodebuku)
                            .addComponent(txtkodepinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpeminjam)
                            .addComponent(txtkodedenda, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtkodepinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtkodedenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(txtpeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkonfirmasiActionPerformed
        String kodedenda = txtkodedenda.getText();
        String kodeuseranggota = txtpeminjam.getText();
        String kodepinjam = txtkodepinjam.getText(); // Perbaiki ini menjadi txtkodebuku
        String kodebuku = txtkodebuku.getText();

        Denda denda = new Denda(kodedenda, kodepinjam, kodebuku, this.kodeuser, kodeuseranggota);
        boolean result = denda.simpanDenda();

        if (result) {
            JOptionPane.showMessageDialog(this, "Konfirmasi berhasil.", "Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
            txtkodedenda.setText("");
            txtpeminjam.setText("");
            txtkodepinjam.setText("");
            txtkodebuku.setText("");
            model.setRowCount(0); // Hapus semua baris dalam tabel
            showData();
        } else {
            JOptionPane.showMessageDialog(this, "Konfirmasi gagal.", "Konfirmasi", JOptionPane.ERROR_MESSAGE);txtkodedenda.setText("");
            txtkodedenda.setText("");
            txtpeminjam.setText("");
            txtkodepinjam.setText("");
            txtkodebuku.setText("");
            model.setRowCount(0); // Hapus semua baris dalam tabel
            showData();
        }        
    }//GEN-LAST:event_btnkonfirmasiActionPerformed

    private void tabledendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledendaMouseClicked
        int selectedRow = tabledenda.getSelectedRow();

        if (selectedRow >= 0) {
            String selectedKodedenda = (String) tabledenda.getValueAt(selectedRow, 1);
            String selectedKodepinjam = (String) tabledenda.getValueAt(selectedRow, 3);
            String selectedKodebuku = (String) tabledenda.getValueAt(selectedRow, 4);
            String selectedKodeuser = (String) tabledenda.getValueAt(selectedRow, 5);

            txtkodedenda.setText(selectedKodedenda);
            txtkodepinjam.setText(selectedKodepinjam);
            txtkodebuku.setText(selectedKodebuku);
            txtpeminjam.setText(selectedKodeuser);
        }
    }//GEN-LAST:event_tabledendaMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        this.dispose();
        formMenu.setVisible(true); 
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            FormMenu formMenu = new FormMenu("", ""); 
            String kodeuser = formMenu.getKodeUser();
            String role = formMenu.getRole();
            new FormDenda(formMenu, kodeuser, role).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnkonfirmasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledenda;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtkodedenda;
    private javax.swing.JTextField txtkodepinjam;
    private javax.swing.JTextField txtpeminjam;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
